
services:
  irods-server:
    platform: linux/amd64
    container_name: irods-server
    image: "ghcr.io/wtsi-npg/ub-18.04-irods-4.2.11:latest"
    ports:
      - "127.0.0.1:1247:1247"
      - "127.0.0.1:20000-20199:20000-20199"
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "1247"]
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 12

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      IRODS_ENVIRONMENT_FILE: "/app/tests/.irods/irods_environment.json"
      IRODS_PASSWORD: "irods"
      IRODS_VERSION: "4.2.11"
    depends_on:
      irods-server:
        condition: service_healthy
